name: Frontend

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run build
      - run: docker rmi -f test-frontend:latest
      - run: docker build -t test-frontend:latest .
      - run: docker rm -f test-frontend
      - run: docker run -d --name test-frontend -p 3001:3000 test-frontend:latest